name: Build application image workflow
run-name: Run image build
on:
  workflow_call:
    inputs:
      build-env:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      version-file:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      task-definition:
        required: true
        type: string
      task-container-name:
        required: true
        type: string

env:
  AWS_REGION: ap-northeast-1

jobs:
  Build-and-Push-Image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.build-env }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Environment Variables Injection and Determine Dockerfile Path
        env:
          ENVVARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$ENVVARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
          DOCKERFILE="${{ inputs.dockerfile }}"
          echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
          echo "Using Dockerfile: $DOCKERFILE"

      - name: Build Docker Image
        id: build-image
        run: |
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}
          RECAPTHCA_SITEKEY=${{ secrets.RECAPTHCA_SITEKEY }}
          envsubst < .env.template > .env
          cat .env
          VERSION=$(grep '"version"' ${{ inputs.version-file }} | sed 's/.*"version":\ "\(.*\)",/\1/')
          IMAGE_TAG=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:$VERSION
          docker buildx build --platform=linux/amd64 -t $IMAGE_TAG -f ${{ env.DOCKERFILE }} .
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT
          # push the built image to ecr repository
          docker push $IMAGE_TAG

      - name: Upload .env to config bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: .env
          AWS_REGION: ${{ env.AWS_REGION }}
          S3_BUCKET: ${{ env.AWS_S3_CONFIG_BUCKET }}
          S3_KEY: .test.env
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Fill in the new image ID in the Amazon ECS task definition
#        id: task-def
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: ${{ inputs.task-definition }}
#          container-name: ${{ inputs.task-container-name }}
#          image: ${{ steps.build-image.outputs.image }}
